namespace Suzuryg.LocalSwitchGenerator
{
    internal class Constants
    {
        public static readonly string SystemName = "LocalSwitchGenerator";
        public static readonly string AssetBaseDir = $"Assets/{SystemName}/AutoGenerated";

        public static readonly string Prefix_Interact = "Interact_";
        public static readonly string Prefix_On = "On_";
        public static readonly string Prefix_Off = "Off_";
    }
}
