namespace Suzuryg.LocalSwitchGenerator
{
    internal class Constants
    {
        public static readonly string PackageName = "jp.suzuryg.local-switch-generator";
        public static readonly string SystemName = "LocalSwitchGenerator";
        public static readonly string AssetBaseDir = $"Assets/{SystemName}/AutoGenerated";

        public static readonly string Prefix_Interact = "Interact_";
        public static readonly string Prefix_On = "On_";
        public static readonly string Prefix_Off = "Off_";

        public static readonly string Key_Locale = $"{PackageName}.locale";

        public static readonly string Guid_ja_JP = "e130c45d353e4be4083b944158265a13";
    }
}
